services:

    php:
        container_name: ${APP_NAME}-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                user: lucas
                uid: 1000
        volumes:
            - .:/var/www/html
        ports:
            - ${APP_PORT}:80
        networks:
            - mysql_net
        restart: always
        depends_on:
            - db

    db:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.4.2
        environment:
            MYSQL_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD:
            MYSQL_RANDOM_ROOT_PASSWORD:
        volumes:
            - db_volume:/var/lib/mysql
        ports:
            - ${DB_EXTERNAL_PORT}:3306
        networks:
            - mysql_net
        restart: always

    grafana:
        container_name: ${APP_NAME}-grafana
        image: grafana/grafana:10.2.2
        ports:
            - 3000:3000
        networks:
            - mysql_net
        restart: always
        volumes:
            - grafana_volume:/var/lib/grafana

volumes:
    db_volume:
    grafana_volume:

networks:
    mysql_net:
        driver: bridge
